#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE auth_db OWNER $POSTGRES_USER;
    CREATE DATABASE clothe_db OWNER $POSTGRES_USER;
    CREATE DATABASE order_db OWNER $POSTGRES_USER;
    CREATE DATABASE staff_db OWNER $POSTGRES_USER;
    CREATE DATABASE manager_db OWNER $POSTGRES_USER;
    CREATE DATABASE catalog_db OWNER $POSTGRES_USER;
    CREATE DATABASE pay_db OWNER $POSTGRES_USER;
    CREATE DATABASE ship_db OWNER $POSTGRES_USER;
    CREATE DATABASE comment_db OWNER $POSTGRES_USER;
    CREATE DATABASE recommender_db OWNER $POSTGRES_USER;
    CREATE DATABASE electronic_db OWNER $POSTGRES_USER;
    CREATE DATABASE food_db OWNER $POSTGRES_USER;
    CREATE DATABASE toy_db OWNER $POSTGRES_USER;
    CREATE DATABASE furniture_db OWNER $POSTGRES_USER;
    CREATE DATABASE cosmetic_db OWNER $POSTGRES_USER;
    CREATE DATABASE sport_db OWNER $POSTGRES_USER;
    CREATE DATABASE stationery_db OWNER $POSTGRES_USER;
    CREATE DATABASE appliance_db OWNER $POSTGRES_USER;
    CREATE DATABASE jewelry_db OWNER $POSTGRES_USER;
    CREATE DATABASE pet_db OWNER $POSTGRES_USER;
EOSQL
